version: '3'

services:
  app:
    restart: always
    container_name: ansar
    environment: 
     - TZ=Asia/Makassar
     build:
       context: -
      ports: 
       - "8012:8012"
      volumes:
       -.:/app
      command: gunicorn projek.wsgi:application --bind 0.0.0.0:8012 --workers 12