# Generated by Django 4.2.11 on 2024-05-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
